plugins { id 'com.android.application' }

android {
    namespace 'fr.manubotelho.mesnotes'
    compileSdk 35

    defaultConfig {
        applicationId 'fr.manubotelho.mesnotes'
        minSdk 26
        targetSdk 35
        versionCode 4
        versionName '1.3'
    }

    signingConfigs {
        release {
            if (System.getenv('NOTES_KEYSTORE')) {
                storeFile file(System.getenv('NOTES_KEYSTORE'))
                storePassword 'android'
                keyAlias 'mnm'
                keyPassword 'android'
            }
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.core:core:1.15.0'
}
