package com.mesmessages.app;

import android.app.Notification;
import android.service.notification.NotificationListenerService;
import android.service.notification.StatusBarNotification;

/**
 * Local-only listener for notifications generated by Google Messages.
 * It runs only after the phone owner explicitly enables notification access
 * in Android settings. No data leaves the device.
 */
public class MessageNotificationService extends NotificationListenerService {
    private static final String GOOGLE_MESSAGES = "com.google.android.apps.messaging";

    @Override
    public void onNotificationPosted(StatusBarNotification notification) {
        saveIfGoogleMessage(notification);
    }

    @Override
    public void onListenerConnected() {
        super.onListenerConnected();
        StatusBarNotification[] current = getActiveNotifications();
        if (current != null) {
            for (StatusBarNotification notification : current) {
                saveIfGoogleMessage(notification);
            }
        }
    }

    private void saveIfGoogleMessage(StatusBarNotification sbn) {
        if (sbn == null || !GOOGLE_MESSAGES.equals(sbn.getPackageName())) return;
        Notification n = sbn.getNotification();
        if (n == null || n.extras == null) return;

        CharSequence title = n.extras.getCharSequence(Notification.EXTRA_TITLE);
        CharSequence body = n.extras.getCharSequence(Notification.EXTRA_BIG_TEXT);
        if (body == null || body.length() == 0) {
            body = n.extras.getCharSequence(Notification.EXTRA_TEXT);
        }
        if (body == null || body.length() == 0) return;

        CapturedMessageStore store = new CapturedMessageStore(this);
        store.save(title == null ? "Google Messages" : title.toString(),
                title == null ? "" : title.toString(),
                body.toString(),
                sbn.getPostTime(),
                CapturedMessageStore.DIRECTION_RECEIVED);
        store.close();
    }
}
